### ISSUE TITLE
Autocomplete for 'transform: translate()' turns into 'transform: translate()()'

### ISSUE THREAD

**Issue by geoffchan23** [styled-components/vscode-styled-components#219]
When I go to type 'transform: translate()' it turns it into 'transform: translate()()'. Not sure if this is specifically a plugin issue, but I thought I would bring it up.

**Comment by paprikman** [comment]
Same happens for the `url()` and other stuff. In addition, if you type something like `:not` and hit 'enter' for autocompletion to happen, it will result in `::not`. VERY annoying.

**Comment by JaxCavalera** [comment]
Also happens for the following:
- width: 100%
AutoCompletes to: `width: 100%100%`

- box-sizin
AutoCompletes to: `box-box-sizing`

Essentially AutoComplete isn't removing the original text it is meant to be replacing. I've tested if this happens in other files such as a *.ts file or with React components and in both cases it is working as expected which means it's likely specific to this extension.

**Comment by j0hnm4r5** [comment]
This is happening to me too (particularly the `100%100%` thing), and it's extremely frustrating.

Also, negative numbers will do `margin-left: --2rem;`

It is definitely this extension. It stops when the extension is disabled, and doesn't happen in normal CSS files.

**Comment by jasonwilliams** [comment]
I think this is fixed in 1.0.0
please re-raise if its still. there

**Comment by ramilamparo** [comment]
If anyone is still having issues with this, inserting the following line in the vscode settings will fix it.
"editor.acceptSuggestionOnCommitCharacter": false

**Comment by paprikman** [comment]
The issue was fixed, but it does not seem to solve the source of the problem.
Both in 1.0.0 release and in current 1.6.6 if you type, say, `::selection` or `:hover` and hit enter, then you will get `:::selection` or `:hover` respectively.

In addition, if you enter, say, `flex-`, hit esc to close the intellisense window and then continue with typing `flow`, hit enter, you will get `flex-flex-flow`. I am not getting that in regular css code.

**Comment by jasonwilliams** [comment]
@paprikman could you raise a new issue for that? Thanks

**Comment by mattbrannon** [comment]
I'm still having an issue with this. Not only do I get double `()()` but even when I type every character of `translate` it auto completes to `translate3d`. I also get weird auto completions when using percentages. 

![vscode-styled-components-bug](https://user-images.githubusercontent.com/36570183/134426400-3a1cba05-3b13-4a63-b4de-9fb5373634fc.gif)
  
Seems related to https://github.com/styled-components/vscode-styled-components/issues/325 and https://github.com/styled-components/vscode-styled-components/issues/322
